### ISSUE TITLE
Remove underscore

### ISSUE THREAD

**Issue by kyeme** [dastgirp/Scripts#8]
Suggestion in https://github.com/dastgir/Scripts/tree/master/Lua/multi-tools

I suggest to remove the underscore ( _ ) in DisplayName when using mergeidnum converter. Thanks!
![ss1](https://user-images.githubusercontent.com/4656578/32048666-d7b8226e-ba7c-11e7-9f75-9af05591e361.jpg)

**Comment by dastgir** [comment]
It should be read as it is from displaynametable. You want the tool to auto convert those intended _ to spaces?

**Comment by kyeme** [comment]
Yes please :)

**Comment by dastgir** [comment]
Done https://github.com/dastgir/Scripts/commit/c787816ef7a21138447187981ce77d31a32ee86d

**Comment by kyeme** [comment]
Hello, underscore ( _ ) inside unidentifiedResourceName and identifiedResourceName also removed and it will cause sprite error ingame.

**Comment by kyeme** [comment]
If slot of item is 0, result become `slotCount = ,` and may cause error.
